name: Joel's Journal
markdown: redcarpet
highlighter: pygments
description: "My personal place to write about the things I find interesting. Programming, Lisp, Ruby, Emacs, etc."
url: http://joelmccracken.github.io
permalink: /entries/:title/
excerpt_separator: ""
